version: '3'
services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    ports:
      - "25565:25565"
    environment:
      ONLINE_MODE: "FALSE"
      EULA: "TRUE"
      MEMORY: "1G"
    restart: on-failure
    stdin_open: true
    volumes:
      - ./data:/data
  geyser:
    image: alfanse/geyser:1.1
    container_name: geyser
    ports:
      - "19132:19132/udp"
    environment:
      TZ: "Europe/London"
      GEYSER_MIN_MEM: "512M"
      GEYSER_MAX_MEM: "512M"
      REMOTE_ADDRESS: "minecraft"
      REMOTE_AUTH_TYPE: "offline"
    restart: unless-stopped
    volumes:
      - ./geyser:/geyser
    links:
      - minecraft
    depends_on:
      - minecraft