version: '3'
services:
  bind:
    container_name: dns
    restart: always
    image: sameersbn/bind:9.11.3-20190706
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    - "10000:10000/tcp"
    volumes:  
    - ./dns/data:/data
