version: '3'
services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    ports:
      - "25565:25565"
    environment:
      ONLINE_MODE: "FALSE"
      EULA: "TRUE"
      MEMORY: "2G"
    restart: on-failure
    stdin_open: true
    volumes:
      - ./data:/data
  geyser:
    image: alfanse/geyser:latest
    container_name: geyser
    ports:
      - "19132:19132/udp"
    environment:
      TZ: "Europe/London"
      GEYSER_MIN_MEM: "512M"
      GEYSER_MAX_MEM: "512M"
      REMOTE_ADDRESS: "minecraft"
      REMOTE_AUTH_TYPE: "offline"
    restart: unless-stopped
    volumes:
      - ./geyser:/geyser
    links:
      - minecraft
    depends_on:
      - minecraft

# dns for connecting switch to minecraft by re-routing mco.lbsg.net. to nas.
#  bind:
#    container_name: dns
#    restart: always
#    image: sameersbn/bind:9.11.3-20190706
#    ports:
#    - "53:53/udp"
#    - "53:53/tcp"
#    - "10000:10000/tcp"
#    volumes:
#    - ./dns/data:/data
#    links:
#      - geyser
#    depends_on:
#      - geyser
